default_language_version:
    python: python3
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=20000']
    -   id: detect-private-key
    -   id: check-json
    # -   id: pretty-format-json
    -   id: check-merge-conflict
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        types: [file, python]
        args: ["--max-line-length=150", "--ignore=E203,W503,W605"]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
    -   id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
        additional_dependencies: [tokenize-rt==3.2.0, types-requests, types-pytz]
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black-jupyter
        args: [--line-length=120]
    -   id: black
        args: [--line-length=120]
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
    -   id: bandit
        args: [-r, -ll,-ii, "-s=B301,B303"]
-   repo: https://github.com/PyCQA/isort
    rev: 5.11.5
    hooks:
    -   id: isort
        args: ["--profile", "black", "--filter-files"]
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.3.1
  hooks:
    - id: nbqa-flake8
      args: ["--max-line-length=120", "--ignore=E203,W503,E402"]
    - id: nbqa-black
      args: [--line-length=120]
